# Base image is `Manjaro Linux`

# ---------------------------------------------------------------------------
# Layer 1: Base image, minimum installation only for chezmoi apply
#          And install that must be used in our environment.
# ---------------------------------------------------------------------------
FROM docker.io/manjarolinux/base:latest AS base

LABEL org.opencontainers.image.title="dotfiles-manjaro"


FROM base AS no-config-base
# Get arguments from Outer ENV values
ARG HOST_UID # GIVEN BY `Makefile` as a default
ARG HOST_GID # GIVEN BY `Makefile` as a default
ARG USERNAME # GIVEN BY `.env` (required; build fails if not set)

# Remap the existing `builder` user/group to the host uid/gid (and rename it
# to $USERNAME when set) so bind-mounted files keep correct ownership.
# manjarolinux/base ships `builder` at 1000:1000, so uid/gid only change when
# they differ from the host.
RUN if [ "$(id -g builder)" != "${HOST_GID}" ]; then \
        groupmod -g ${HOST_GID} builder; \
    fi \
 && if [ "$(id -u builder)" != "${HOST_UID}" ] || [ "$(id -g builder)" != "${HOST_GID}" ]; then \
        usermod -u ${HOST_UID} -g ${HOST_GID} builder; \
    fi \
 && if [ -n "${USERNAME}" ] && [ "${USERNAME}" != "builder" ]; then \
        usermod -l ${USERNAME} -d /home/${USERNAME} -m builder \
     && groupmod -n ${USERNAME} builder; \
    fi
USER ${USERNAME}

# ---------------------------------------------------------------------------
# Layer 2: chezmoi apply our dotfiles
# ---------------------------------------------------------------------------
# TODO: Run `pacman config` and install some required packages (like `base-devel`)
#          (Only for first time. and then it's cached.
#           it is used for installation of packages that requires some ENV value
#           it should be overridden when `chezmoi apply` is run again
#           in the container.)
