/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 19
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 14
#define ALIAS_COUNT 0
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_lua_start_marker_line = 1,
  sym_viml_start_marker_line = 2,
  sym_end_marker_line = 3,
  aux_sym_line_token1 = 4,
  anon_sym_LF = 5,
  sym_wrapper_start_line = 6,
  sym_wrapper_end_line = 7,
  sym_document = 8,
  sym_hook_block = 9,
  sym_line = 10,
  sym_hook_line = 11,
  aux_sym_document_repeat1 = 12,
  aux_sym_hook_block_repeat1 = 13,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_lua_start_marker_line] = "lua_start_marker_line",
  [sym_viml_start_marker_line] = "viml_start_marker_line",
  [sym_end_marker_line] = "end_marker_line",
  [aux_sym_line_token1] = "line_token1",
  [anon_sym_LF] = "\n",
  [sym_wrapper_start_line] = "wrapper_start_line",
  [sym_wrapper_end_line] = "wrapper_end_line",
  [sym_document] = "document",
  [sym_hook_block] = "hook_block",
  [sym_line] = "line",
  [sym_hook_line] = "hook_line",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_hook_block_repeat1] = "hook_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_lua_start_marker_line] = sym_lua_start_marker_line,
  [sym_viml_start_marker_line] = sym_viml_start_marker_line,
  [sym_end_marker_line] = sym_end_marker_line,
  [aux_sym_line_token1] = aux_sym_line_token1,
  [anon_sym_LF] = anon_sym_LF,
  [sym_wrapper_start_line] = sym_wrapper_start_line,
  [sym_wrapper_end_line] = sym_wrapper_end_line,
  [sym_document] = sym_document,
  [sym_hook_block] = sym_hook_block,
  [sym_line] = sym_line,
  [sym_hook_line] = sym_hook_line,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_hook_block_repeat1] = aux_sym_hook_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_lua_start_marker_line] = {
    .visible = true,
    .named = true,
  },
  [sym_viml_start_marker_line] = {
    .visible = true,
    .named = true,
  },
  [sym_end_marker_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_wrapper_start_line] = {
    .visible = true,
    .named = true,
  },
  [sym_wrapper_end_line] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_hook_block] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_hook_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_hook_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 2,
  [8] = 4,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 9,
  [14] = 10,
  [15] = 11,
  [16] = 16,
  [17] = 17,
  [18] = 16,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (eof) ADVANCE(2);
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == 'E') ADVANCE(17);
      if (lookahead == 'l') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(37);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_lua_start_marker_line);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_viml_start_marker_line);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_end_marker_line);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '\n') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '\n') ADVANCE(4);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == 'E') ADVANCE(17);
      if (lookahead == 'l') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '<') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '<') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == 'F') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == 'O') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '_') ADVANCE(30);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == 'a') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == 'l') ADVANCE(23);
      if (lookahead == '}') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == 'u') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == 'u') ADVANCE(20);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '{') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '{') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '{') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '{') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '{') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '{') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '}') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '}') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '}') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_wrapper_start_line);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_wrapper_end_line);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_lua_start_marker_line] = ACTIONS(1),
    [sym_viml_start_marker_line] = ACTIONS(1),
    [sym_end_marker_line] = ACTIONS(1),
    [aux_sym_line_token1] = ACTIONS(1),
    [sym_wrapper_start_line] = ACTIONS(1),
    [sym_wrapper_end_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(17),
    [sym_hook_block] = STATE(3),
    [sym_line] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_lua_start_marker_line] = ACTIONS(5),
    [sym_viml_start_marker_line] = ACTIONS(7),
    [sym_end_marker_line] = ACTIONS(9),
    [aux_sym_line_token1] = ACTIONS(11),
    [sym_wrapper_start_line] = ACTIONS(9),
    [sym_wrapper_end_line] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_hook_block] = STATE(4),
    [sym_line] = STATE(12),
    [sym_hook_line] = STATE(4),
    [aux_sym_hook_block_repeat1] = STATE(4),
    [sym_lua_start_marker_line] = ACTIONS(13),
    [sym_viml_start_marker_line] = ACTIONS(15),
    [sym_end_marker_line] = ACTIONS(17),
    [aux_sym_line_token1] = ACTIONS(19),
    [sym_wrapper_start_line] = ACTIONS(21),
    [sym_wrapper_end_line] = ACTIONS(21),
  },
  [STATE(3)] = {
    [sym_hook_block] = STATE(5),
    [sym_line] = STATE(5),
    [aux_sym_document_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_lua_start_marker_line] = ACTIONS(5),
    [sym_viml_start_marker_line] = ACTIONS(7),
    [sym_end_marker_line] = ACTIONS(25),
    [aux_sym_line_token1] = ACTIONS(11),
    [sym_wrapper_start_line] = ACTIONS(25),
    [sym_wrapper_end_line] = ACTIONS(25),
  },
  [STATE(4)] = {
    [sym_hook_block] = STATE(6),
    [sym_line] = STATE(12),
    [sym_hook_line] = STATE(6),
    [aux_sym_hook_block_repeat1] = STATE(6),
    [sym_lua_start_marker_line] = ACTIONS(13),
    [sym_viml_start_marker_line] = ACTIONS(15),
    [sym_end_marker_line] = ACTIONS(27),
    [aux_sym_line_token1] = ACTIONS(19),
    [sym_wrapper_start_line] = ACTIONS(21),
    [sym_wrapper_end_line] = ACTIONS(21),
  },
  [STATE(5)] = {
    [sym_hook_block] = STATE(5),
    [sym_line] = STATE(5),
    [aux_sym_document_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_lua_start_marker_line] = ACTIONS(31),
    [sym_viml_start_marker_line] = ACTIONS(34),
    [sym_end_marker_line] = ACTIONS(37),
    [aux_sym_line_token1] = ACTIONS(40),
    [sym_wrapper_start_line] = ACTIONS(37),
    [sym_wrapper_end_line] = ACTIONS(37),
  },
  [STATE(6)] = {
    [sym_hook_block] = STATE(6),
    [sym_line] = STATE(12),
    [sym_hook_line] = STATE(6),
    [aux_sym_hook_block_repeat1] = STATE(6),
    [sym_lua_start_marker_line] = ACTIONS(43),
    [sym_viml_start_marker_line] = ACTIONS(46),
    [sym_end_marker_line] = ACTIONS(49),
    [aux_sym_line_token1] = ACTIONS(51),
    [sym_wrapper_start_line] = ACTIONS(54),
    [sym_wrapper_end_line] = ACTIONS(54),
  },
  [STATE(7)] = {
    [sym_hook_block] = STATE(8),
    [sym_line] = STATE(12),
    [sym_hook_line] = STATE(8),
    [aux_sym_hook_block_repeat1] = STATE(8),
    [sym_lua_start_marker_line] = ACTIONS(13),
    [sym_viml_start_marker_line] = ACTIONS(15),
    [sym_end_marker_line] = ACTIONS(57),
    [aux_sym_line_token1] = ACTIONS(19),
    [sym_wrapper_start_line] = ACTIONS(21),
    [sym_wrapper_end_line] = ACTIONS(21),
  },
  [STATE(8)] = {
    [sym_hook_block] = STATE(6),
    [sym_line] = STATE(12),
    [sym_hook_line] = STATE(6),
    [aux_sym_hook_block_repeat1] = STATE(6),
    [sym_lua_start_marker_line] = ACTIONS(13),
    [sym_viml_start_marker_line] = ACTIONS(15),
    [sym_end_marker_line] = ACTIONS(59),
    [aux_sym_line_token1] = ACTIONS(19),
    [sym_wrapper_start_line] = ACTIONS(21),
    [sym_wrapper_end_line] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(63), 2,
      sym_viml_start_marker_line,
      aux_sym_line_token1,
    ACTIONS(61), 5,
      ts_builtin_sym_end,
      sym_lua_start_marker_line,
      sym_end_marker_line,
      sym_wrapper_start_line,
      sym_wrapper_end_line,
  [12] = 2,
    ACTIONS(67), 2,
      sym_viml_start_marker_line,
      aux_sym_line_token1,
    ACTIONS(65), 5,
      ts_builtin_sym_end,
      sym_lua_start_marker_line,
      sym_end_marker_line,
      sym_wrapper_start_line,
      sym_wrapper_end_line,
  [24] = 2,
    ACTIONS(71), 2,
      sym_viml_start_marker_line,
      aux_sym_line_token1,
    ACTIONS(69), 5,
      ts_builtin_sym_end,
      sym_lua_start_marker_line,
      sym_end_marker_line,
      sym_wrapper_start_line,
      sym_wrapper_end_line,
  [36] = 2,
    ACTIONS(75), 2,
      sym_viml_start_marker_line,
      aux_sym_line_token1,
    ACTIONS(73), 4,
      sym_lua_start_marker_line,
      sym_end_marker_line,
      sym_wrapper_start_line,
      sym_wrapper_end_line,
  [47] = 2,
    ACTIONS(63), 2,
      sym_viml_start_marker_line,
      aux_sym_line_token1,
    ACTIONS(61), 4,
      sym_lua_start_marker_line,
      sym_end_marker_line,
      sym_wrapper_start_line,
      sym_wrapper_end_line,
  [58] = 2,
    ACTIONS(67), 2,
      sym_viml_start_marker_line,
      aux_sym_line_token1,
    ACTIONS(65), 4,
      sym_lua_start_marker_line,
      sym_end_marker_line,
      sym_wrapper_start_line,
      sym_wrapper_end_line,
  [69] = 2,
    ACTIONS(71), 2,
      sym_viml_start_marker_line,
      aux_sym_line_token1,
    ACTIONS(69), 4,
      sym_lua_start_marker_line,
      sym_end_marker_line,
      sym_wrapper_start_line,
      sym_wrapper_end_line,
  [80] = 1,
    ACTIONS(77), 1,
      anon_sym_LF,
  [84] = 1,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
  [88] = 1,
    ACTIONS(81), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 12,
  [SMALL_STATE(11)] = 24,
  [SMALL_STATE(12)] = 36,
  [SMALL_STATE(13)] = 47,
  [SMALL_STATE(14)] = 58,
  [SMALL_STATE(15)] = 69,
  [SMALL_STATE(16)] = 80,
  [SMALL_STATE(17)] = 84,
  [SMALL_STATE(18)] = 88,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_hook_block_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_hook_block_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_hook_block_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_hook_block_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_hook_block_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hook_block, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hook_block, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hook_block, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hook_block, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hook_line, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hook_line, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [79] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dpp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "dpp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
