#!/usr/bin/env python3
"""Regenerate per-layer install lists and the 02-installed-programs AUTO-GEN block.

Source of truth: ``dependencies/packages.toml`` (schema=1).

Outputs (all derived, do not hand-edit):
  - ``dependencies/layer_<N>/<manager>.txt``  — one install list per layer (N>=1)
    and per list-based manager (pacman / paru / nix / uv / cargo / mise). Layer 0
    (already in the base image) and ``custom`` (bespoke install path) produce no
    txt. ``mise`` lines are rendered as ``<name>@latest`` (bare ``mise install
    <tool>`` reads a ``mise.toml``, not latest).
  - The AUTO-GEN block in ``docs/specifications/02-installed-programs.md``
    (between the ``installed-programs`` markers), rendered as per-layer tables.

Invoke via ``make gen-deps`` from the repo root.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

import tomllib

SCHEMA = 1

# Resolved from programs/generate_deps/main.py:
#   parents[0]=generate_deps  parents[1]=programs  parents[2]=repo root
SCRIPT = Path(__file__).resolve()
REPO_ROOT = SCRIPT.parents[2]
DEPS_DIR = REPO_ROOT / "dependencies"
TOOLS_TOML = DEPS_DIR / "packages.toml"
DOC_PATH = REPO_ROOT / "docs" / "specifications" / "02-installed-programs.md"

# Managers that install from a flat package list -> emit a .txt file.
# `mise` lines are rendered as `<name>@latest` (bare `mise install <tool>`
# reads a `mise.toml`, not latest); see `render_packages_txt`.
LIST_MANAGERS = ("pacman", "paru", "nix", "uv", "cargo", "mise")
# Doc-only managers: declared in packages.toml (so they appear in the
# spec 02 AUTO-GEN doc block and satisfy invariant I5) but NOT installed
# from a generated `layer_<N>/<manager>.txt` list — they have a bespoke
# install path in the Containerfile. `custom` covers packages with a
# hand-written install step (e.g. `paru`, bootstrapped via `makepkg`,
# which cannot also be a `paru -S` target).
DOC_ONLY_MANAGERS = ("custom",)
ALL_MANAGERS = LIST_MANAGERS + DOC_ONLY_MANAGERS

# (layer, manager) pairs that always have a generated install list file,
# even when no entries exist. Required because the Containerfile COPYs
# `dependencies/layer_3/cargo.txt`, `dependencies/layer_4/paru.txt`, and
# `dependencies/layer_3/mise.txt` unconditionally; a missing file breaks
# the build. Keeping these files generator-owned satisfies spec 02 §9
# criterion #10 (never hand-edited).
EXPECTED_EMPTY_FILES: tuple[tuple[int, str], ...] = (
    (3, "cargo"),
    (4, "paru"),
    (3, "mise"),
)

MD_BEGIN = "<!-- BEGIN AUTO-GEN: installed-programs -->"
MD_END = "<!-- END AUTO-GEN: installed-programs -->"

TXT_HEADER = (
    "# AUTO-GENERATED by programs/generate_deps/main.py -- do not edit by hand.\n"
    "# Source: dependencies/packages.toml -- run `make gen-deps` to regenerate.\n"
)


def fail(msg: str) -> None:
    print(f"generate_deps: {msg}", file=sys.stderr)
    sys.exit(1)


def load_tools() -> list[dict]:
    if not TOOLS_TOML.is_file():
        fail(f"source of truth not found: {TOOLS_TOML.relative_to(REPO_ROOT)}")
    with TOOLS_TOML.open("rb") as f:
        data = tomllib.load(f)
    if data.get("schema") != SCHEMA:
        fail(f"unsupported schema {data.get('schema')!r}; expected {SCHEMA}")
    tools = data.get("tool", [])
    if not isinstance(tools, list):
        fail("[[tool]] must be an array of tables")
    for t in tools:
        validate(t)
    return tools


def validate(t: dict) -> None:
    name = t.get("name")
    if not isinstance(name, str) or not name:
        fail(f"entry missing `name`: {t!r}")
    mgr = t.get("manager")
    if mgr not in ALL_MANAGERS:
        fail(f"{name}: unknown manager {mgr!r} (allowed: {ALL_MANAGERS})")
    layer = t.get("layer")
    if not isinstance(layer, int) or isinstance(layer, bool) or layer < 0:
        fail(f"{name}: `layer` must be a non-negative integer, got {layer!r}")
    hc = t.get("has_configs")
    if not isinstance(hc, bool):
        fail(f"{name}: `has_configs` must be bool, got {hc!r}")
    desc = t.get("description")
    if desc is not None and not isinstance(desc, str):
        fail(f"{name}: `description` must be a string, got {desc!r}")


def group_by_layer(tools: list[dict]) -> dict[int, list[dict]]:
    by_layer: dict[int, list[dict]] = defaultdict(list)
    for t in tools:
        by_layer[t["layer"]].append(t)
    return by_layer


def render_packages_txt(layer: int, manager: str, tools: list[dict]) -> str:
    """One package name per line, sorted, with inline `# description` when set."""
    lines = [
        TXT_HEADER,
        f"# manager: {manager} | layer: {layer} | packages: {len(tools)}",
        "",
    ]
    for t in sorted(tools, key=lambda x: x["name"]):
        # `mise` lines carry an `@latest` suffix: bare `mise install <tool>`
        # reads a `mise.toml` (not latest), so the version must be explicit.
        # Other list managers keep bare names.
        line = f"{t['name']}@latest" if manager == "mise" else t["name"]
        desc = t.get("description")
        if desc:
            line = f"{line}  # {desc}"
        lines.append(line)
    lines.append("")
    return "\n".join(lines)


def _md_escape(cell: str) -> str:
    return cell.replace("|", "\\|").replace("\n", " ")


def render_doc_block(tools: list[dict]) -> str:
    by_layer = group_by_layer(tools)
    lines = [
        "Rendered from "
        "[`../../dependencies/packages.toml`](../../dependencies/packages.toml) "
        "via `make gen-deps` (`programs/generate_deps/main.py`). "
        "Do not edit by hand.",
        "",
    ]
    for layer in sorted(by_layer):
        entries = sorted(by_layer[layer], key=lambda x: (x["manager"], x["name"]))
        heading = (
            f"#### Layer {layer} — already in the base image"
            if layer == 0
            else f"#### Layer {layer} — install list"
        )
        lines += [heading, ""]
        lines += [
            "| name | manager | configs | description |",
            "|---|---|---|---|",
        ]
        for t in entries:
            configs = "yes" if t["has_configs"] else "no"
            desc = t.get("description") or ""
            lines.append(
                f"| `{_md_escape(t['name'])}` | {t['manager']} | {configs} "
                f"| {_md_escape(desc)} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_if_changed(path: Path, content: str) -> bool:
    """Write only when content differs; return True if written."""
    if path.is_file() and path.read_text() == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def write_txt_files(by_layer: dict[int, list[dict]]) -> int:
    written = 0
    for layer, tools in by_layer.items():
        if layer < 1:
            # Layer 0 is pre-installed in the base image; no install list.
            continue
        by_mgr: dict[str, list[dict]] = defaultdict(list)
        for t in tools:
            by_mgr[t["manager"]].append(t)
        for mgr in LIST_MANAGERS:
            entries = by_mgr.get(mgr)
            if not entries:
                continue
            out = DEPS_DIR / f"layer_{layer}" / f"{mgr}.txt"
            if write_if_changed(out, render_packages_txt(layer, mgr, entries)):
                written += 1
    # Emit empty install-list files for (layer, manager) pairs that the
    # build expects unconditionally (see EXPECTED_EMPTY_FILES above).
    for layer, mgr in EXPECTED_EMPTY_FILES:
        existing = [
            t for t in by_layer.get(layer, []) if t["manager"] == mgr
        ]
        if existing:
            continue  # already emitted by the main loop
        out = DEPS_DIR / f"layer_{layer}" / f"{mgr}.txt"
        if write_if_changed(out, render_packages_txt(layer, mgr, [])):
            written += 1
    return written


def write_doc(block: str) -> bool:
    src = DOC_PATH.read_text()
    if MD_BEGIN not in src or MD_END not in src:
        fail(
            f"{DOC_PATH.relative_to(REPO_ROOT)} missing AUTO-GEN markers "
            f"({MD_BEGIN!r} / {MD_END!r}); add them around the section to regenerate"
        )
    before, _, rest = src.partition(MD_BEGIN)
    _, _, after = rest.partition(MD_END)
    new = f"{before}{MD_BEGIN}\n{block}{MD_END}{after}"
    return write_if_changed(DOC_PATH, new)


def main() -> int:
    tools = load_tools()
    by_layer = group_by_layer(tools)
    n_txt = write_txt_files(by_layer)
    doc_written = write_doc(render_doc_block(tools))
    layers = sorted(by_layer)
    print(
        f"generate_deps: layers={layers} txt_written={n_txt} doc_updated={doc_written}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
