# TODO: make template and manage per-each user, when this repo is shared.
git:
    identity_default:
        name: kkiyama117
        email: k.kiyama117@gmail.com
        signingkey: A1E4E20240EA5BAA
    identities: {}